"""edit status

Revision ID: 3942c7bea6d0
Revises: 
Create Date: 2024-03-10 08:33:00.161760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3942c7bea6d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.drop_column('vote_count')

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote_count', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
